default:
  batch_size: 128
  early_stopping: true
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  num_epochs: 500
  patience: 15
  use_fraction: 1.0
gru_0:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_1:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_16:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_17:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_18:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_19:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_2:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_20:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_21:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_22:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_23:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_3:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_4:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_5:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 2
  patience: 15
  use_fraction: 1.0
gru_6:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
gru_7:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: gru
  num_epochs: 500
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_10:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_11:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_12:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_13:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_14:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_15:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_24:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_25:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_26:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_27:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_28:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_29:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_30:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_31:
  batch_size: 128
  dropout: 0.3
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: wav2vec
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 256
  model_name: transformer
  num_epochs: 500
  num_heads: 4
  num_layers: 3
  patience: 15
  use_fraction: 1.0
transformer_8:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0001
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
transformer_9:
  batch_size: 128
  dropout: 0.1
  early_stopping: true
  gpu_vis_dev: '0'
  input_type: cqt
  lr: 0.0005
  min_f1_epochs: 500
  min_f1_threshold: 0.2
  model_dim: 128
  model_name: transformer
  num_epochs: 500
  num_heads: 2
  num_layers: 2
  patience: 15
  use_fraction: 1.0
